#!/usr/bin/env python3
"""
Star Rewards — Growth data layer migration (Plan A).

Makes the "growth record" a real longitudinal asset instead of a screenshot
of behaviors+redeemed rows. Everything is ADDITIVE:
  - ALTER profiles      ADD birth_date, bio_note
  - ALTER behaviors     ADD dimension   (tags a star event with a growth area)
  - CREATE milestones   (non-transactional growth moments)
  - CREATE growth_notes (parent narrative)
  - CREATE child_voice  (child's own words)

SAFETY:
  1. Full DB backup to /tmp/star_rewards_backup_<ts>.sql BEFORE any change.
  2. Idempotent: column existence checked via information_schema; tables via
     CREATE TABLE IF NOT EXISTS. Re-running is a no-op if everything exists.
  3. Additive DDL only.

Run:  /Users/xuversa/.workbuddy/binaries/python/envs/default/bin/python scripts/migrate_growth_data.py
"""
import re, os, datetime, pymysql

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV = os.path.join(ROOT, "api", ".env.php")

def parse_env():
    src = open(ENV).read()
    def g(k):
        m = re.search(r"'%s'\s*=>\s*'([^']*)'" % k, src)
        return m.group(1) if m else None
    return {
        "host": g("DB_HOST"), "port": int(g("DB_PORT")),
        "db": g("DB_NAME"), "user": g("DB_USER"), "pass": g("DB_PASS"),
    }

cfg = parse_env()
TS = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
BACKUP = f"/tmp/star_rewards_backup_{TS}.sql"

def conn():
    return pymysql.connect(host=cfg["host"], port=cfg["port"], user=cfg["user"],
                           password=cfg["pass"], database=cfg["db"],
                           connect_timeout=20, charset="utf8mb4")

def column_exists(cur, table, col):
    cur.execute(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_schema = %s AND table_name = %s AND column_name = %s",
        (cfg["db"], table, col))
    return bool(cur.fetchone())

def backup(c):
    cur = c.cursor()
    cur.execute("SHOW TABLES")
    tables = [r[0] for r in cur.fetchall()]
    lines = ["-- Star Rewards full backup " + TS,
             "-- Generated by scripts/migrate_growth_data.py",
             "SET FOREIGN_KEY_CHECKS=0;", ""]
    for t in tables:
        cur.execute("SELECT COUNT(*) FROM `%s`" % t)
        n = cur.fetchone()[0]
        cur.execute("SELECT * FROM `%s`" % t)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
        lines.append("-- table %s (%d rows)" % (t, n))
        lines.append("DROP TABLE IF EXISTS `%s`;" % t)
        cur.execute("SHOW CREATE TABLE `%s`" % t)
        lines.append(cur.fetchone()[1] + ";")
        for row in rows:
            vals = []
            for v in row:
                if v is None:
                    vals.append("NULL")
                elif isinstance(v, (bytes,)):
                    vals.append("0x" + v.hex())
                else:
                    vals.append("'" + str(v).replace("\\", "\\\\").replace("'", "\\'") + "'")
            lines.append("INSERT INTO `%s` (%s) VALUES (%s);" % (
                t, ", ".join("`%s`" % c for c in cols), ", ".join(vals)))
        lines.append("")
    open(BACKUP, "w").write("\n".join(lines))
    print("BACKUP -> " + BACKUP + " (%d tables)" % len(tables))

def main():
    c = conn()
    try:
        cur = c.cursor()
        changes = []

        # ── profiles: birth_date + bio_note ──
        for col, ddl in [
            ("birth_date", "DATE NULL"),
            ("bio_note", "TEXT NULL"),
        ]:
            if not column_exists(cur, "profiles", col):
                print("ALTER profiles ADD %s %s" % (col, ddl))
                cur.execute("ALTER TABLE profiles ADD COLUMN `%s` %s" % (col, ddl))
                changes.append("profiles.%s" % col)

        # ── behaviors: dimension ──
        if not column_exists(cur, "behaviors", "dimension"):
            print("ALTER behaviors ADD dimension VARCHAR(20) NULL")
            cur.execute("ALTER TABLE behaviors ADD COLUMN `dimension` VARCHAR(20) NULL")
            changes.append("behaviors.dimension")

        # ── milestones ──
        cur.execute("SHOW TABLES LIKE 'milestones'")
        if not cur.fetchone():
            print("CREATE milestones")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS milestones (
                    id BIGINT NOT NULL AUTO_INCREMENT,
                    family_id BIGINT NOT NULL,
                    profile_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    category VARCHAR(40) NOT NULL DEFAULT '其他',
                    title VARCHAR(255) NOT NULL,
                    detail TEXT NULL,
                    occurred_on DATE NULL,
                    photo_url VARCHAR(2048) DEFAULT '',
                    created_at TIMESTAMP NULL DEFAULT current_timestamp(),
                    PRIMARY KEY (id),
                    KEY idx_ms_family (family_id),
                    KEY idx_ms_profile (profile_id),
                    CONSTRAINT fk_ms_family FOREIGN KEY (family_id) REFERENCES families (id) ON DELETE CASCADE,
                    CONSTRAINT fk_ms_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
            changes.append("milestones")

        # ── growth_notes ──
        cur.execute("SHOW TABLES LIKE 'growth_notes'")
        if not cur.fetchone():
            print("CREATE growth_notes")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS growth_notes (
                    id BIGINT NOT NULL AUTO_INCREMENT,
                    family_id BIGINT NOT NULL,
                    profile_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    body TEXT NULL,
                    mood VARCHAR(20) DEFAULT 'happy',
                    occurred_on DATE NULL,
                    photo_urls TEXT NULL,
                    created_at TIMESTAMP NULL DEFAULT current_timestamp(),
                    PRIMARY KEY (id),
                    KEY idx_gn_family (family_id),
                    KEY idx_gn_profile (profile_id),
                    CONSTRAINT fk_gn_family FOREIGN KEY (family_id) REFERENCES families (id) ON DELETE CASCADE,
                    CONSTRAINT fk_gn_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
            changes.append("growth_notes")

        # ── child_voice ──
        cur.execute("SHOW TABLES LIKE 'child_voice'")
        if not cur.fetchone():
            print("CREATE child_voice")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS child_voice (
                    id BIGINT NOT NULL AUTO_INCREMENT,
                    family_id BIGINT NOT NULL,
                    profile_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    content TEXT NOT NULL,
                    recorded_on DATE NULL,
                    created_at TIMESTAMP NULL DEFAULT current_timestamp(),
                    PRIMARY KEY (id),
                    KEY idx_cv_family (family_id),
                    KEY idx_cv_profile (profile_id),
                    CONSTRAINT fk_cv_family FOREIGN KEY (family_id) REFERENCES families (id) ON DELETE CASCADE,
                    CONSTRAINT fk_cv_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
            changes.append("child_voice")

        if not changes:
            print("Nothing to do — growth data layer already exists (idempotent).")
            return

        print("Backing up database before migration...")
        backup(c)
        c.commit()
        print("OK: applied %d change(s): %s" % (len(changes), ", ".join(changes)))
        print("MIGRATION DONE.")
    except Exception as e:
        c.rollback()
        raise
    finally:
        c.close()

if __name__ == "__main__":
    main()
