#!/usr/bin/env python3
"""
Star Rewards — Family Sharing migration runner.

SAFETY:
  1. Takes a FULL backup of all tables to /tmp/star_rewards_backup_<ts>.sql BEFORE any change.
  2. Idempotent: if `families` table already exists, aborts (nothing to do).
  3. Additive DDL only (CREATE + nullable ALTER + backfill + NOT NULL + FK).
  4. Verifies row counts after backfill; prints a clear report.

Run:  /Users/xuversa/.workbuddy/binaries/python/envs/default/bin/python scripts/migrate_family.py
"""
import re, sys, os, datetime, pymysql

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV = os.path.join(ROOT, "api", ".env.php")

def parse_env():
    src = open(ENV).read()
    def g(k):
        m = re.search(r"'%s'\s*=>\s*'([^']*)'" % k, src)
        return m.group(1) if m else None
    return {
        "host": g("DB_HOST"), "port": int(g("DB_PORT")),
        "db": g("DB_NAME"), "user": g("DB_USER"), "pass": g("DB_PASS"),
    }

def conn():
    return pymysql.connect(host=cfg["host"], port=cfg["port"], user=cfg["user"],
                           password=cfg["pass"], database=cfg["db"],
                           connect_timeout=20, charset="utf8mb4")

cfg = parse_env()
TS = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
BACKUP = f"/tmp/star_rewards_backup_{TS}.sql"

INVITE_ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"  # no 0/O/1/I/L

def gen_code(cur, length=6):
    import random
    for _ in range(50):
        c = "".join(random.choice(INVITE_ALPHABET) for _ in range(length))
        cur.execute("SELECT 1 FROM families WHERE invite_code=%s", (c,))
        if not cur.fetchone():
            return c
    raise RuntimeError("could not generate unique invite code")

def backup(c):
    cur = c.cursor()
    cur.execute("SHOW TABLES")
    tables = [r[0] for r in cur.fetchall()]
    lines = ["-- Star Rewards full backup " + TS,
             "-- Generated by scripts/migrate_family.py",
             "SET FOREIGN_KEY_CHECKS=0;", ""]
    for t in tables:
        cur.execute("SELECT COUNT(*) FROM `%s`" % t)
        n = cur.fetchone()[0]
        cur.execute("SELECT * FROM `%s`" % t)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
        if not rows:
            lines.append(f"-- {t}: 0 rows")
            continue
        for row in rows:
            vals = []
            for v in row:
                if v is None:
                    vals.append("NULL")
                elif isinstance(v, (bytes,)):
                    vals.append("0x" + v.hex())
                elif isinstance(v, (int, float)):
                    vals.append(str(v))
                else:
                    s = str(v).replace("\\", "\\\\").replace("'", "''").replace("\n", "\\n").replace("\r", "\\r")
                    vals.append("'" + s + "'")
            lines.append("INSERT INTO `%s` (%s) VALUES (%s);" % (
                t, ", ".join("`%s`" % c for c in cols), ", ".join(vals)))
        lines.append("")
    with open(BACKUP, "w") as f:
        f.write("\n".join(lines) + "\n")
    return tables

def main():
    c = conn()
    try:
        cur = c.cursor()
        # ---- idempotency guard ----
        cur.execute("SHOW TABLES LIKE 'families'")
        if cur.fetchone():
            print("[ABORT] `families` table already exists — migration already applied. Nothing to do.")
            return 0

        print("[1/5] Backing up all tables to", BACKUP)
        tables = backup(c)
        print("      tables:", ", ".join(tables))

        print("[2/5] Applying DDL (families, family_members, family_id columns)...")
        ddl = [
            """CREATE TABLE families (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                name VARCHAR(100) NOT NULL DEFAULT '我的家庭',
                invite_code VARCHAR(8) NOT NULL,
                invite_expires_at TIMESTAMP NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY uniq_invite (invite_code)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci""",
            """CREATE TABLE family_members (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                family_id BIGINT NOT NULL,
                user_id BIGINT NOT NULL,
                role ENUM('owner','member') NOT NULL DEFAULT 'member',
                display_name VARCHAR(60) NOT NULL DEFAULT '',
                joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY uniq_family_user (family_id, user_id),
                KEY idx_fm_user (user_id),
                CONSTRAINT fk_fm_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
                CONSTRAINT fk_fm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci""",
            "ALTER TABLE profiles ADD COLUMN family_id BIGINT NULL",
            "ALTER TABLE behaviors ADD COLUMN family_id BIGINT NULL",
            "ALTER TABLE gifts ADD COLUMN family_id BIGINT NULL",
            "ALTER TABLE redeemed_gifts ADD COLUMN family_id BIGINT NULL",
        ]
        for stmt in ddl:
            cur.execute(stmt)
        c.commit()

        print("[3/5] Data migration: create a solo family (owner) for every existing user, assign profiles...")
        cur.execute("SELECT id, email FROM users ORDER BY id")
        users = cur.fetchall()
        migrated = 0
        for (uid, email) in users:
            cur.execute("SELECT 1 FROM family_members WHERE user_id=%s LIMIT 1", (uid,))
            if cur.fetchone():
                continue
            local = email.split("@", 1)[0] if email else str(uid)
            code = gen_code(cur)
            cur.execute("INSERT INTO families (name, invite_code, invite_expires_at) VALUES (%s, %s, NULL)",
                        ("%s 的家庭" % local, code))
            fid = cur.lastrowid
            cur.execute("INSERT INTO family_members (family_id, user_id, role, display_name) VALUES (%s, %s, 'owner', %s)",
                        (fid, uid, local[:60]))
            cur.execute("UPDATE profiles SET family_id=%s WHERE user_id=%s AND family_id IS NULL", (fid, uid))
            migrated += 1
        c.commit()
        print("      users processed:", len(users), "| families created:", migrated)

        print("[4/5] Backfill family_id on behaviors/gifts/redeemed via profile join...")
        joins = [
            ("behaviors", "b"),
            ("gifts", "g"),
            ("redeemed_gifts", "r"),
        ]
        for tbl, alias in joins:
            cur.execute("UPDATE `%s` %s JOIN profiles p ON %s.profile_id = p.id SET %s.family_id = p.family_id WHERE %s.family_id IS NULL"
                        % (tbl, alias, alias, alias, alias))
            print("      %s: %d rows updated" % (tbl, cur.rowcount))

        # tighten NOT NULL + FK + indexes
        cur.execute("ALTER TABLE profiles MODIFY COLUMN family_id BIGINT NOT NULL")
        cur.execute("ALTER TABLE profiles ADD KEY idx_profile_family (family_id)")
        cur.execute("ALTER TABLE profiles ADD CONSTRAINT fk_profile_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE")
        cur.execute("ALTER TABLE behaviors MODIFY COLUMN family_id BIGINT NOT NULL")
        cur.execute("ALTER TABLE behaviors ADD KEY idx_behavior_family (family_id)")
        cur.execute("ALTER TABLE gifts MODIFY COLUMN family_id BIGINT NOT NULL")
        cur.execute("ALTER TABLE gifts ADD KEY idx_gift_family (family_id)")
        cur.execute("ALTER TABLE redeemed_gifts MODIFY COLUMN family_id BIGINT NOT NULL")
        cur.execute("ALTER TABLE redeemed_gifts ADD KEY idx_redeemed_family (family_id)")
        c.commit()

        print("[5/5] Verifying...")
        cur.execute("SELECT COUNT(*) FROM profiles WHERE family_id IS NULL OR family_id=0")
        bad_profiles = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM behaviors WHERE family_id IS NULL OR family_id=0")
        bad_beh = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM gifts WHERE family_id IS NULL OR family_id=0")
        bad_gifts = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM redeemed_gifts WHERE family_id IS NULL OR family_id=0")
        bad_red = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM families")
        nfam = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM family_members")
        nmem = cur.fetchone()[0]

        print("      families=%d  family_members=%d" % (nfam, nmem))
        print("      NULL family_id -> profiles:%d behaviors:%d gifts:%d redeemed:%d"
              % (bad_profiles, bad_beh, bad_gifts, bad_red))
        if bad_profiles or bad_beh or bad_gifts or bad_red:
            print("[FAIL] Some rows still have NULL family_id. Backup at", BACKUP, "— aborting commit.")
            c.rollback()
            return 1
        print("\n[SUCCESS] Migration applied. Backup saved to:")
        print("   ", BACKUP)
        print("To restore: load that file into the database (SET FOREIGN_KEY_CHECKS=0 first).")
        return 0
    except Exception as e:
        c.rollback()
        print("[ERROR]", repr(e))
        print("Backup (if taken) at", BACKUP)
        return 1
    finally:
        c.close()

if __name__ == "__main__":
    sys.exit(main())
