#!/usr/bin/env python3
"""
Star Rewards — Analytics events table migration runner.

SAFETY:
  1. Takes a FULL backup of all tables to /tmp/star_rewards_backup_<ts>.sql BEFORE any change.
  2. Idempotent: if `analytics_events` table already exists, aborts (nothing to do).
  3. Additive DDL only (CREATE TABLE IF NOT EXISTS).
  4. Verifies the table after creation; prints a clear report.

Run:  /Users/xuversa/.workbuddy/binaries/python/envs/default/bin/python scripts/migrate_analytics.py
"""
import re, os, datetime, pymysql

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV = os.path.join(ROOT, "api", ".env.php")

def parse_env():
    src = open(ENV).read()
    def g(k):
        m = re.search(r"'%s'\s*=>\s*'([^']*)'" % k, src)
        return m.group(1) if m else None
    return {
        "host": g("DB_HOST"), "port": int(g("DB_PORT")),
        "db": g("DB_NAME"), "user": g("DB_USER"), "pass": g("DB_PASS"),
    }

cfg = parse_env()
TS = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
BACKUP = f"/tmp/star_rewards_backup_{TS}.sql"

def conn():
    return pymysql.connect(host=cfg["host"], port=cfg["port"], user=cfg["user"],
                           password=cfg["pass"], database=cfg["db"],
                           connect_timeout=20, charset="utf8mb4")

def backup(c):
    cur = c.cursor()
    cur.execute("SHOW TABLES")
    tables = [r[0] for r in cur.fetchall()]
    lines = ["-- Star Rewards full backup " + TS,
             "-- Generated by scripts/migrate_analytics.py",
             "SET FOREIGN_KEY_CHECKS=0;", ""]
    for t in tables:
        cur.execute("SELECT COUNT(*) FROM `%s`" % t)
        n = cur.fetchone()[0]
        cur.execute("SELECT * FROM `%s`" % t)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
        lines.append("-- table %s (%d rows)" % (t, n))
        lines.append("DROP TABLE IF EXISTS `%s`;" % t)
        cur.execute("SHOW CREATE TABLE `%s`" % t)
        create = cur.fetchone()[1]
        lines.append(create + ";")
        for row in rows:
            vals = []
            for v in row:
                if v is None:
                    vals.append("NULL")
                elif isinstance(v, (bytes,)):
                    vals.append("0x" + v.hex())
                else:
                    vals.append("'" + str(v).replace("\\", "\\\\").replace("'", "\\'") + "'")
            lines.append("INSERT INTO `%s` (%s) VALUES (%s);" % (
                t, ", ".join("`%s`" % c for c in cols), ", ".join(vals)))
        lines.append("")
    open(BACKUP, "w").write("\n".join(lines))
    print("BACKUP -> " + BACKUP + " (%d tables)" % len(tables))

def main():
    c = conn()
    try:
        cur = c.cursor()
        cur.execute("SHOW TABLES LIKE 'analytics_events'")
        if cur.fetchone():
            print("analytics_events already exists — nothing to do (idempotent).")
            return

        print("Backing up database before migration...")
        backup(c)

        print("Creating analytics_events table...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS analytics_events (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                user_id INT UNSIGNED NULL,
                family_id INT UNSIGNED NULL,
                event VARCHAR(64) NOT NULL,
                meta JSON NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                INDEX idx_event (event),
                INDEX idx_user (user_id),
                INDEX idx_created (created_at)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        """)

        cur.execute("SHOW TABLES LIKE 'analytics_events'")
        if not cur.fetchone():
            raise RuntimeError("analytics_events not created")

        cur.execute("SELECT COUNT(*) FROM analytics_events")
        n = cur.fetchone()[0]
        print("OK: analytics_events created (rows=%d)." % n)
        print("MIGRATION DONE.")
    finally:
        c.close()

if __name__ == "__main__":
    main()
